---
language: ruby
rvm:
  - 2.0.0
  - 2.1.1
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: GovDViLCjDKdoGK35Y462dswcOAWnl+gB/wBJw0NzJk6cnzQDGcBBQlc/2b0p09RzvvVpjB2/p61wuatbBnJCU9sYgWNid3fz01lf3gD7KNypxbGoJBSkUTvHM0CYtdOiV1Owt2mdt8eQauRrvWvjR62rEbwB6TrJMook20YB2k=
  on:
    all_branches: true
    tags: true
